[project]
name = "iamacooker-agent"
version = "0.1.0"
description = "The agent component of IAmACooker"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.0.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 