[project]
name = "howtocook-mcp"
version = "0.1.0"
description = "The MCP server component of HowToCook"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "httpx>=0.28.1",
    "pydantic>=2.7.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 